name = "Kuramodel"
uuid = "62645e5b-daf0-4994-810f-795952a33356"
authors = ["EnricoCaprioglio"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
